name: build_run_and_test

on:
  push:
    branches:
      - mod4_ast2
#      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pylint
        pip3 install joblib
        pip3 install scikit-learn
        pip3 install pandas
        pip3 install pyyaml
        pip3 install pytest
    - name: train the model 
      run: |
        echo "current working directory: ".$PWD
        cd bikeshare_model
        echo "changed working directory to: ".$PWD
        # create local directories
        mkdir pipeline
        
        # run the pipeline
        python3 train_pipeline.py --config config.yml 

    - name: run predict 
      run: |
        echo "current working directory: ".$PWD
        cd bikeshare_model
        echo "changed working directory to: ".$PWD
        
        # run the Predict
        python3 predict.py --config config.yml

    - name: run testcases
      run: |
        cd bikeshare_model
        echo "changed working directory to: ".$PWD
        
        # run the test-case
        pytest -v

  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
#    - name: Docker login
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}  
        
    - name: execute docker run
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: "bikeshare"
          DOCKER_REPO_NAME: "bikeshare"
      run: |
        echo "working directory to: ".$PWD
        echo "building docker image from current folder"
        docker build -t ${{ DOCKER_REPO_NAME }} .
        
        # displaying docker images
        docker images

