name: build_run_and_test

on:
  push:
    branches:
      - mod4_ast2
#      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements/requirements.txt
        pip3 install pylint
        pip3 install pytest
        
    - name: train the model 
      run: |
        echo "current working directory: ".$PWD
        cd bikeshare_model
        echo "changed working directory to: ".$PWD
        # create local directories
        mkdir pipeline
        
        # run the pipeline
        python3 train_pipeline.py --config config.yml 

    - name: run predict 
      run: |
        echo "current working directory: ".$PWD
        cd bikeshare_model
        echo "changed working directory to: ".$PWD
        
        # run the Predict
        python3 predict.py --config config.yml

    - name: run testcases
      run: |
        cd bikeshare_model
        echo "changed working directory to: ".$PWD
        
        # run the test-case
        pytest -v

  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: "mphaniram"
        password: ""  

#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}  

    - name: create bikeshare distribution
      run: |
        echo "working directory to: ".$PWD
        python3 setup.py bdist_wheel
        
    - name: execute docker run
      env:
          RELEASE_NAME: "bikeshare2"
          DOCKER_REPO_NAME: "mphaniram/bikeshare2"
          DOCKER_IMG_VERSION: "22.0.4"
      run: |
        echo "working directory to: ".$PWD
        echo "building docker image from current folder"
        echo "Docker repo name: ".${{ env.DOCKER_REPO_NAME }}
        docker build -t ${{ env.DOCKER_REPO_NAME }} .
        
        # add latest and specific release-version to image
        docker tag ${{ env.DOCKER_REPO_NAME }}:latest ${{ env.DOCKER_REPO_NAME }}:${{ env.DOCKER_IMG_VERSION }}
        
        # displaying docker images
        docker images

    - name: docker push
      env:
          RELEASE_NAME: "bikeshare2"
          DOCKER_REPO_NAME: "mphaniram/bikeshare2"
          DOCKER_IMG_VERSION: "22.0.4"
      run: |
        echo "pushing docker image  - ".${{ env.DOCKER_REPO_NAME }}.":latest"
        echo "pushing docker image  - ".${{ env.DOCKER_REPO_NAME }}:${{ env.DOCKER_IMG_VERSION }}
        docker push ${{ env.DOCKER_REPO_NAME }}:latest 
        docker push ${{ env.DOCKER_REPO_NAME }}:${{ env.DOCKER_IMG_VERSION }}
